modLoader = "javafml"
loaderVersion="[45,)" #mandatory
license = "All Rights Reserved"

[[mods]]
modId = "toolkit"
version = "${version}"
displayName = "Toolkit"
authors="Sunekaer"
description='''
This mod adds bunch of useful commands
'''

[[dependencies.toolkit]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toolkit]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toolkit]]
modId = "architectury"
mandatory = true
versionRange = "[8.2.89,)"
ordering = "AFTER"
side = "BOTH"
