modLoader = "javafml"
loaderVersion="[49,)" #mandatory
license = "All Rights Reserved"

[[mods]]
modId = "toolkit"
version = "${version}"
displayName = "Toolkit"
authors="Sunekaer"
description='''
This mod adds bunch of useful commands
'''

[[dependencies.toolkit]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toolkit]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toolkit]]
modId = "architectury"
mandatory = true
versionRange = "[11.0.11,)"
ordering = "AFTER"
side = "BOTH"
