modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license = "All Rights Reserved"
[[mods]] #mandatory
modId="toolkit" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Tool Kit" #mandatory
authors="Sunekaer" #optional
description='''
This mod adds bunch of useful commands
'''
[[dependencies.toolkit]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.toolkit]]
modId="minecraft"
mandatory=true
versionRange="[1.18,)"
ordering="NONE"
side="BOTH"