modLoader = "javafml"
loaderVersion="[1,)" #mandatory
license = "All Rights Reserved"

[[mods]]
modId = "toolkit"
version = "${version}"
displayName = "Toolkit"
authors="Sunekaer"
description='''
This mod adds bunch of useful commands
'''

[[dependencies.toolkit]]
modId = "neoforge"
required = true
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toolkit]]
modId = "minecraft"
required = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toolkit]]
modId = "architectury"
required = true
versionRange = "[11.0.11,)"
ordering = "AFTER"
side = "BOTH"
