modLoader = "javafml"
loaderVersion="[2,)"
license = "All Rights Reserved"

[[mods]]
modId = "toolkit"
version = "${version}"
displayName = "Toolkit"
authors="Sunekaer"
description='''
This mod adds bunch of useful commands
'''

[[dependencies.toolkit]]
modId = "neoforge"
required = true
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.toolkit]]
modId = "minecraft"
required = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "toolkit-common.mixins.json"

[[mixins]]
config = "toolkit.mixins.json"
