name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    uses: nanite/workflows/.github/workflows/release.yml@v1.3
    with:
      java-version: 21
      gradle-tasks: build publish publishMods
    secrets:
      nanite-token: ${{ secrets.NANITE_DEPLOY }}
      curse-token: ${{ secrets.CURSE_DEPLOY }}
      modrinth-token: ${{ secrets.MODRINTH_TOKEN }}